[package]
name = "developer-anecdotes"
version = "0.1.0"
authors = ["jim4067 <jimmyimpulse2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
rand = "0.8.3"
